name: Trigger Deployments for Frontend and Backend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.commits.*.modified, 'frontend/') || contains(github.event.commits.*.added, 'frontend/') || contains(github.event.commits.*.removed, 'frontend/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Vercel Deployment
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"gitSource": {"type": "github", "repoId": "${{ secrets.VERCEL_REPO_ID }}", "ref": "main"}}' \
            https://api.vercel.com/v13/deployments
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  deploy-backend:
    runs-on: ubuntu-latest
    if: contains(github.event.commits.*.modified, 'backend/') || contains(github.event.commits.*.added, 'backend/') || contains(github.event.commits.*.removed, 'backend/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Render Deployment
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "${{ secrets.RENDER_SERVICE_ID }}"}' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
